### ISSUE TITLE
Weird problem with midpoint constraints

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#208]
See [top.zip](https://github.com/whitequark/solvespace/files/328813/top.zip). It's unsatisfied. I see no reason it should be.

**Comment by whitequark** [comment]
Another problem of the same class: 
[top.zip](https://github.com/whitequark/solvespace/files/329983/top.zip)

**Comment by whitequark** [comment]
Looks like in 2nd case the culprit is a duplicated vertical constraint. This error should be handled better.

**Comment by whitequark** [comment]
In 2nd case this is a duplicated vertical and horizontal constraint. We should show an error when those constraints are added, not a much more confusing one afterwards.

**Comment by Evil-Spirit** [comment]
the problem is what we don't put all the equations (for dof analysis) into Jacobian, so we have no ability to alert it like "overconstrained"

**Comment by whitequark** [comment]
How can we fix this?

**Comment by Evil-Spirit** [comment]
we just can lookup all the equations and try to find. or we can try to add all the equations to Jacobian. Test and reporting will run in natural way (this is only for the first time when we add constraint).

**Comment by whitequark** [comment]
Let's try the latter one (but be careful about slowing down, it is already quite slow)

**Comment by Evil-Spirit** [comment]
It's not slow because of solver I think.

**Comment by Evil-Spirit** [comment]
hm... it looks like this is not the fix(don't solve by substitution)

**Comment by Evil-Spirit** [comment]
Oh, no, i've missed and commented not related line inside FindWhichToRemoveToFixJacobian(). When we comment SolveBySubstitution() inside Solve() we get the right "redundant" message.

**Comment by Evil-Spirit** [comment]
@whitequark,
I've pushed the prototype. I propose not adding the constraints which causes errors like overdefining the system or not converging from the start.

**Comment by whitequark** [comment]
But this leaves the sketch in a broken state afterwards, if solving has moved the stuff around.

**Comment by Evil-Spirit** [comment]
@whitequark, did you mean changed? if rudundant constraints solve sketch and copy it's parameters, it will be changed. So it just can be fixed by not coping parameters when test-solving.

**Comment by Evil-Spirit** [comment]
fixed here https://github.com/Evil-Spirit/solvespace/commit/d7a80b44df3c749d2fb9dca3682236dfd0b2b24b

**Comment by whitequark** [comment]
Actually, no, it is not fixed. Try this:
![2693](https://cloud.githubusercontent.com/assets/54771/19916353/386ba964-a0b1-11e6-90f0-11f1f1c79cbf.png)
then create a vertical constraint on hypotenuse.

**Comment by Evil-Spirit** [comment]
@whitequark, what's wrong with it?

**Comment by whitequark** [comment]
@Evil-Spirit Sketch becomes broken, even though the constraint is not actually added.

**Comment by Evil-Spirit** [comment]
@whitequark, Strange behaviour, can you attach screenshot? It seems I don't have such problem.

**Comment by Evil-Spirit** [comment]
may be you are testing without this commit? https://github.com/Evil-Spirit/solvespace/commit/d7a80b44df3c749d2fb9dca3682236dfd0b2b24b

**Comment by whitequark** [comment]
The original problem (with that commit) is as follows:
![2694](https://cloud.githubusercontent.com/assets/54771/19958232/68570e0e-a195-11e6-9039-71780f7aabb3.png)

Now I am thinking, it's actually good; it should show the "unsolvable constraints" thing in the text window to demonstrate that there is a conflict. But the text in text window should be replaced with something else, like "cannot add this constraint because of a conflict with one of these:" or something.

**Comment by Evil-Spirit** [comment]
@whitequark,
Yes, the text in messagebox must be rewritten.

**Comment by Evil-Spirit** [comment]
@whitequark, more improvements
https://github.com/Evil-Spirit/solvespace/commit/9e6d030458bea9d3c1adafb85780ca12260daca5
https://github.com/Evil-Spirit/solvespace/commit/e11fa8fb82140daee90111198dd30c9729560f7c

**Comment by Evil-Spirit** [comment]
@whitequark 
you can merge this

**Comment by whitequark** [comment]
I don't like the UI very much. We used to have red screen when nonsensical constraints are inserted and when a dof is removed. Now we have red screen when a dof is removed, and a popup when a nonsensical constraint is inserted. And this interrupts workflow even more.

I need to think about fixing this best.

**Comment by Evil-Spirit** [comment]
@whitequark 
I only can say what this is much better for user not allowing add unsolveable and redundant constraints. Anyway, the standart way to fix it just press ctrl+z. This breaks workflow, not interrupt since both of them interrupts workflow some way. I agree what user must see what's wrong with constraints, can select and decide what to do. But for me (and for some other users) is just good to auto-remove new defective constraint immediately. I think this can be an option at least. But what do you think about auto-marking constraint with reference if it makes sketch redundant? This is usefult and not breaking anything

**Comment by whitequark** [comment]
> I only can say what this is much better for user not allowing add unsolveable and redundant constraints.

Yes. I think we need this functionality in some form, just not yet sure which.

> But what do you think about auto-marking constraint with reference if it makes sketch redundant? This is usefult and not breaking anything

It is but it doesn't work for most constraints.

**Comment by Evil-Spirit** [comment]
> Yes. I think we need this functionality in some form, just not yet sure which.

This can be an option "Disable red-screen" which also changes behaviour of dragging (just reverting parameters when sketch becomes unsolveable). I actually imlemented such workflow and there is no problems with this.

> It is but it doesn't work for most constraints.

Yes, this can be only applicable for constraints with dimension label. Actually, this is just standart approach for CAD applications.

**Comment by Evil-Spirit** [comment]
@whitequark,
What we are going to do with?
I think we can introduce the flag : dofDirty and do the full dof check without substitution if this flag set. This  flag must be set when we add new constraint and after loading (to analyse old files for problems)
What do you think about this?

**Comment by whitequark** [comment]
@Evil-Spirit sounds good

**Comment by Evil-Spirit** [comment]
@whitequark 
pushed again
https://github.com/Evil-Spirit/solvespace-master/commit/c90a38ddcdbec505ad7bdd335849225e14169374

**Comment by whitequark** [comment]
Merged.
