### ISSUE TITLE
oops at line 644, file /src/drawentity.cpp

### ISSUE THREAD

**Issue by aam2015** [whitequark/solvespace#51]
Built version 2.1 from source today (Dec 23 2015) on an LMDE 2 64-bit system. Importing any of the parts from the assembly example (http://solvespace.com/dl/box-parts.zip) causes an immediate abort with the above error.

I found you can open these files individually from the command line and then save them. After they have been saved, they can be imported without any issues. There are numerous differences between the original and saved files. I've attached the newly saved files.

[assembly2.zip](https://github.com/whitequark/solvespace/files/71400/assembly2.zip)

**Comment by Symbian9** [comment]
@aam2015
Did you read previous issue?
https://github.com/whitequark/solvespace/issues/50

Anyway can you also:

1) ... upload your build for testing

2) ... make fresh build from @Evil-Spirit repo with fixed issues https://github.com/Evil-Spirit/solvespace/commit/02be1d4ca4438ea405141a18c77504524b6707d3

**Comment by whitequark** [comment]
The crash was fixed but there's now some sign error...

**Comment by whitequark** [comment]
Fixed in latest nightly

**Comment by aam2015** [comment]
The latest fix has created a new issue with all the files above. For example, the normals for the slots in base.slvs are now facing in the opposite direction. This obviously causes the slots not to appear in the base.

**Comment by whitequark** [comment]
@aam2015 Hm, correct. @Evil-Spirit, would you please fix this?

**Comment by whitequark** [comment]
This was fixed, however, the entire feature (Workplane on Face) was temporarily rolled back until we have a testsuite. Latest nightly should be able to successfully open all files that exhibited bugs.

**Comment by aam2015** [comment]
I tried the latest nightly (both building from source and the deb) and neither of them seem to have resolved the latest issue. The normals are all still facing in the opposite direction.

**Comment by whitequark** [comment]
That's extremely odd. I've bisected your problem and the commit which caused it has nothing to do with normals. Regardless, I will address this soon.

**Comment by whitequark** [comment]
@aam2015 I'm really sorry for all this breakage and back-and-forth. I've fixed this in https://github.com/whitequark/solvespace/commit/9ce4699753eacaa6033ffc00e85d41080d81bc69 and pushed a new nightly.

**Comment by aam2015** [comment]
@whitequark Thanks for taking the time to fix this.

**Comment by Evil-Spirit** [comment]
I think it is floating bug and it seems it not has been fixed.

**Comment by whitequark** [comment]
Hm, doubt it--my bisecting pointed to a valid cause & I can't reproduce it anywhere anymore.
